---
- name: Install Certbot.
  package: "name={{ item }} state=present"
  with_items: "{{ certbot_packages }}"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "/usr/bin/certbot"
#    certbot_script: "{{ certbot_package }}"
